// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjgfncmxzfileekbdbww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZ2ZuY214emZpbGVla2JkYnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzEyNzQsImV4cCI6MjA2NTE0NzI3NH0.Qze-oJ6p1DdbtD8Q2cieqFNA0pUkUkw6DAPkP3La-Jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);